### ISSUE TITLE
Develop a workflow to run multiple tilt packages with real data

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWorkflows#1]
Based on [tiltIndicatorRunner](https://github.com/2DegreesInvesting/tiltIndicatorRunner) develop parametrized computational documents to run multiple tilt packages with real data.

- [x] https://github.com/2DegreesInvesting/tiltWorkflows/pull/4
- [x] #5 
- [x] #6 
- [x] #14 
- [x] #20 

* Overview (video 4'20")
* [Website](https://2degreesinvesting.github.io/tiltWorkflows/)

**Comment by maurolepore** [comment]
@kalashsinghal could you please point me to the latest workflow file you used to run tilt packages with real data?

**Comment by kalashsinghal** [comment]
@maurolepore I have developed a workflow for your convenience here: https://github.com/2DegreesInvesting/tiltWorkflows/blob/main/tiltIndicator_tiltIndicatorAfter_workflow.Rmd
