### ISSUE TITLE
Add `score_transition_risk` function to create the product and company level output for transition risk score 

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltWorkflows#121]
Dear,

After adding transition risk score to the product level outputs of emission profile and sectors profile, function `score_transition_risk` should be part of the complete tilt work flow. Please add the function!

Usage of the function can be explored using `?score_transition_risk`

**Comment by maurolepore** [comment]
See https://github.com/2DegreesInvesting/tiltWorkflows/issues/139
