### ISSUE TITLE
Resolve R-CMD check after adding `co2_lower` and `co2_upper` in `tiltIndicatorAfter`

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltWorkflows#122]
Relates to [comment](https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/155#pullrequestreview-1881619772)

**Comment by maurolepore** [comment]
See https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/163/commits/5459068524e5f4183a306085f5c22d15ec94b16d#r1503341731
