### ISSUE TITLE
New workflow extends profile_emissions.Rmd and profile_sector.Rmd

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWorkflows#139]
Relates to:

- https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153
- https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/182
- https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/181
- https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/177
- https://github.com/2DegreesInvesting/tiltWorkflows/pull/142

The goal of this issue is to turn Kalash's script into a workflow in tiltWorkflows. The way we created data for Bundesbank (https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153) was had-hoc. To do it again would be really hard. A lot of the knowledge is scattered across a bunch of issues and in our heads. ASAP we need to turn that fragile knowledge into a robust automated workflow.

Note:

* The workflow should not refer to "bundesbank". It should be useful for any bank.
* The most general workflow should be in long format and include the `co2e*` columns.
* The wide format is currently only required for Bundesbank so it should not be part of the general tiltWorkflow. Instead a better fit for that process seems to be an internal-ish helper, maybe in tiltIndicatorAfter:
  * https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/200

----

* [Kalash's script](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153#issuecomment-1966642996)
* [Real data](https://github.com/2DegreesInvesting/tiltIndicatorBefore?tab=readme-ov-file#output-files-from-tiltindicatorbefore).
* [ecoinvent co2 data (ecoinvent-v3.9.1.csv)](https://github.com/2DegreesInvesting/tiltIndicatorBefore/blob/main/input/ecoinvent-v3.9.1.csv).

**Comment by Tilmon** [comment]
@maurolepore as discussed in today's sprint, please note: For future reproducibility, we need all the features created for the Bundesbank output except for the wide format of the `emission_category`.

**Comment by Tilmon** [comment]
Reminder for @AnneSchoenauer and @Tilmon : When reviewing output data, make sure to check if unmatched products are preserved in the same way as it was for the Bundesbank output.

**Comment by maurolepore** [comment]
Closing in favor of https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/201
