### ISSUE TITLE
Run tiltWorkflows with real data

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWorkflows#89]

**Comment by maurolepore** [comment]
@kalashsinghal @ysherstyuk @SKruthoff

From https://2investinginitiative.slack.com/archives/C02NDH6SD3P/p1702461549655419

> Can you please share a link to all the "real" datasets I need to run [the four ](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/index.html#new-api)profile*()[ functions](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/index.html#new-api)?
> ...
> It doesn't matter if the data is incorrect in some way. For my use case what I need most is for the data to be realistically big.

> Specifically, I need one file for each of these parameters. Please help me by explaining which file name I should use in each parameter (sometimes it may not be obvious):


```
# For profile_emissions()
emissions_profile_any_companies:
emissions_profile_products:

# For profile_emissions_upstream()
emissions_profile_any_companies:
emissions_profile_upstream_products:

# For profile_sector()
sector_profile_companies:
sector_profile_any_scenarios:

# For profile_sector_upstream()
sector_profile_upstream_companies:
sector_profile_any_scenarios:
sector_profile_upstream_products:

# For all 
europages_companies:
ecoinvent_activities:
ecoinvent_europages:
ecoinvent_inputs:
isic:
```

**Comment by maurolepore** [comment]
Thanks folks. tiltWorkflows did a good job.

* Took about 1h in total with 16 GB RAM and 4 AMD CPUs.
* With 12 GB RAM the memory usage would reach 100%.
* Required updated dplyr.
* Worked with 250-500 chunks.

https://github.com/2DegreesInvesting/tiltOutput/releases/tag/v0.0.0.9001

**Comment by AnneSchoenauer** [comment]
Nice @maurolepore :), @kalashsinghal does these outputs have already right input data? :)

**Comment by kalashsinghal** [comment]
@AnneSchoenauer Yes it has the right input data :)
